import './globals.css';
import Header from './components/Header';
import CircleInter from './components/CircleInter';
import SquareInter from './components/SquareInter';

export const metadata = {
  title: 'James Yuill | Software Engineer',
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const animationLookup = {
    0: <CircleInter />,
    1: <SquareInter />,
  };
  return (
    <html lang="en">
      <body>
        {animationLookup[0]}
        <Header />
        {children}
      </body>
    </html>
  );
}
