import Header from './components/Header';
import './globals.css';
import MenuContext from './context/MenuContext';

export const metadata = {
  title: 'James Yuill | Software Engineer',
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuContext>
          <Header />
          {children}
        </MenuContext>
      </body>
    </html>
  );
}
